### ISSUE TITLE
Experiment on other data sets

### ISSUE THREAD

**Issue by weiyao1996** [songtaohe/Sat2Graph#2]
This is really a great job, and thank you so much for sharing your source code. Here I have a question.
If I want to try Sat2Graph on my datasets, how to obtain the sample points (_refine_gt_graph_samplepoints.json) and the neighbors (_refine_gt_graph.p) from the ground-truth (_gt.png) please?
Appreciate your help!

**Comment by songtaohe** [comment]
> This is really a great job, and thank you so much for sharing your source code. Here I have a question.
> If I want to try Sat2Graph on my datasets, how to obtain the sample points (_refine_gt_graph_samplepoints.json) and the neighbors (_refine_gt_graph.p) from the ground-truth (_gt.png) please?
> Appreciate your help!

In the current implementation, we take the ground truth graph (from OpenStreetMap) as input (in graph format) and generate the corresponding segmentation mask (_gt.png), the sample points (_refine_gt_graph_samplepoints.json), and the interpolated ground truth graphs (_refine_gt_graph.p). For this part, you can check the code in prepare_dataset/download.py 

If your ground-truth is in segmentation format, then you may have to first convert it to graph format. Unfortunately, there is no code in this repo. I can try to add one if you need it.   



The code to create the sample points and the refined ground truth graphs (_refine_gt_graph.p).

**Comment by engrjavediqbal** [comment]
@songtaohe Thank you for such nice work and implementation. I am trying to evaluate binary segmentation masks using your TOPO implementation, however, I am unable to generate the required graph from binary maps (contains 1, 0). It would be great if you please share or add the scripts to convert the binary segmentation maps to the required graph. 

Thank you.
