### ISSUE TITLE
there is an package error in prepare_data/download.py

### ISSUE THREAD

**Issue by angleyun** [songtaohe/Sat2Graph#3]

**Comment by angleyun** [comment]
Thank you very much for the open source code,  there is an error that ModuleNotFoundError: No module named 'mapdriver' when run prepare_data/download.py.Is mapdriver is your own file,because I could not install it.Looking forward to your reply

**Comment by angleyun** [comment]
> _No description provided._

**Comment by songtaohe** [comment]
Now you should be able to find mapdriver.py. Sorry for this missing file. So far, by default, download.py will download the imagery from mapbox not google. If you want to download google imagery, you can import mapdriver.py as md2. You also need to create an google api key for static map api and update the GOOGLE_API_KEY at line 18 in the mapdriver.py file.

Please feel free to let me know if there is any trouble running the code or if there are some features you need that I can help.

Thank you!
