### ISSUE TITLE
there is an package error in prepare_data/download.py

### ISSUE THREAD

**Issue by angleyun** [songtaohe/Sat2Graph#4]
Thank you very much for the open source code, there is an error that ModuleNotFoundError: No module named 'mapdriver' when run prepare_data/download.py. Is package--mapdriver is your own file,because I could not install it.Looking forward to your reply

**Comment by corentinh271** [comment]
I would also like to thank you for sharing your code. I was actually going to report the exact same issue as I could not find a repository distributing this dependency.

Would it be possible for you to share the full dependency requirements for all the libraries you used, their versions and download links where applicable?

Thanks in advance!

**Comment by songtaohe** [comment]
Thanks for pointing this out! I will update the file soon.

**Comment by songtaohe** [comment]
> Thank you very much for the open source code, there is an error that ModuleNotFoundError: No module named 'mapdriver' when run prepare_data/download.py. Is package--mapdriver is your own file,because I could not install it.Looking forward to your reply

> I would also like to thank you for sharing your code. I was actually going to report the exact same issue as I could not find a repository distributing this dependency.
> 
> Would it be possible for you to share the full dependency requirements for all the libraries you used, their versions and download links where applicable?
> 
> Thanks in advance!



Now you should be able to find mapdriver.py. Sorry for this missing file. So far, by default, download.py will download the imagery from mapbox not google. If you want to download google imagery, you can import mapdriver.py as md2. 

Please feel free to let me know if there is any trouble running the code or if there are some features you need that I can help.

Thank you!

**Comment by angleyun** [comment]
Hello, the download.py you provided before can run successfully, thanks a lot, I would like to ask you to select the length and width of the image in the image training to be 2451, and the length and width of 512 when entering the network training. And the length and width of the image generated in the mapbox_cache folder is 512, because I want to try to preprocess the data on my own data set

**Comment by songtaohe** [comment]
> Hello, the download.py you provided before can run successfully, thanks a lot, I would like to ask you to select the length and width of the image in the image training to be 2451, and the length and width of 512 when entering the network training. And the length and width of the image generated in the mapbox_cache folder is 512, because I want to try to preprocess the data on my own data set

In the original code, we create big image tiles of 2048 pixels. During training, the code rotates the big tile (2048pixels) randomly and uses a random crop with a size of 384 pixels as input to the network. Do you want to change 2048 to 2451 and 384 to 512?

If you want to change the size of the big image tile from 2048 to 2451, you need to provide the corresponding lat/lon bounding box (2451 meter by 2451 meter) to the 'GetMapInRect' function at [here](https://github.com/songtaohe/Sat2Graph/blob/735db431cd7c037b3174c36e65c2b222f591a330/prepare_dataset/download.py#L91). You may need to change a few other places to turn 2048 into 2451 in the 'download.py' file.

During training and inference, you may also need to override the default tile size from 2048 to 2451. Each time you create the Sat2GraphDataLoader object, you can set the ['dataset_image_size'](https://github.com/songtaohe/Sat2Graph/blob/735db431cd7c037b3174c36e65c2b222f591a330/model/dataloader.py#L99) parameter to 2451 (it was 2048 by default). 

To change the network input dimension from 384 to 512, you can use the '-image_size' flag when you run 'train.py'. Just set -image_size to 512 should work. 

You can ignore the images in 'mapbox_cache' folder. Those images are stitched together in the 'GetMapInRect' function and use can just use the output of 'GetMapInRect' function. If you want to increase the spatial resolution, increase the 'zoom' parameter in 'GetMapInRect' function.

Let me know if this answers your question, thanks!

**Comment by angleyun** [comment]
抱歉啊,之前我的表述有问题,是这样子的,非常感谢您之前的解答,比如,我想把您这个代码在公开数据集deepglobe上跑一下,所以这里有几个疑问的点,
1.在您的数据准备部分mapdriver.py代码里边,您使用了overpass-api解析得到xml来得到一些节点信息,但是公开数据集deepglobe中只有简单的彩色影像和二值mask影像,也就是说是不是在数据处理部分,在deepglobe数据集中二值mask是不能得到其节点信息?(因为节点信息关乎到后边的refine_gt_graph_samplepoints.json, refine_gt_graph.p, region_%d_graph_gt.pickle, refine_gt_graph.p等制作)
2.您在训练train.py的train模式是使用的影像长宽大小是352,在进入网络之前的dataloader_train.getBatch函数中samplepoints中的获取时使用了random随机取得overpass,parallel roads,complicated intersections等情况,为什么不直接使用固定的滑动窗口选取input_sat, gt_prob, gt_vector, gt_seg进行训练呢?再一次为我的打扰行为感到抱歉,期待您的解答~

**Comment by angleyun** [comment]
非常感谢您的解答,可能还是得来打扰您,根据您的建议,参考这个repo里面另一个branch中的代码,也就是image2graph.py的文件里边会得到顶点vertices和节点的附近点neighbors,关于生成graph之后与download.py里边的后续与处理过程结合的处理有一些问题想烦扰一下您,1.就是在download.py中下载的操作openstreetmap[md.OSMLoader函数](https://github.com/songtaohe/Sat2Graph/blob/735db431cd7c037b3174c36e65c2b222f591a330/prepare_dataset/download.py#L99)里边在解析xml文件中也就是mapdriver.py文件 [OSMLoader类](https://github.com/songtaohe/Sat2Graph/blob/735db431cd7c037b3174c36e65c2b222f591a330/prepare_dataset/mapdriver.py#L400-L498) ,解析了很多"ways"中的"cycleway","highway"等在二值影像中是没法得到这些信息的得到的
2.如果不需要上边的"ways"关键参数的解析信息,那是不是download.py中neighbors[代码](https://github.com/songtaohe/Sat2Graph/blob/735db431cd7c037b3174c36e65c2b222f591a330/prepare_dataset/download.py#L113)信息是以点序列号为索引的,比如(这是一个点的信息<node id="259841477" lat="20.1355426" lon="-75.2249005" version="5" timestamp="2016-10-12T22:36:02Z" changeset="42842372" uid="496923" user="abellao"/>),而image2graph.py里边得到的neighbors[代码](https://github.com/songtaohe/Sat2Graph/blob/8cf4ed70c51d8581649d34d2db886507f03140e2/prepare_lowres_dataset/image2graph.py#L170-L193),直接将image2graph.py文件中得到的graph图中的neighbors中点的信息是以点的横纵坐标为索引的,比如((1620, 2001)点),所以在转换的时候我不太理解的点在于在download.py中找节点邻接点[node_neighbor](https://github.com/songtaohe/Sat2Graph/blob/8cf4ed70c51d8581649d34d2db886507f03140e2/prepare_dataset/download.py#L115-L118)的获取是按照经纬度进行临近点插入的么(n1key代表经度,n2key代表纬度),因为这两个的索引不太一样,所以真的有点混乱,还望指点迷境,不甚感激

**Comment by songtaohe** [comment]
不好意思，我前一条回复有一些错误，你可以参考这个[文件](https://github.com/songtaohe/Sat2Graph/blob/lowres/prepare_dataset/image2graph.py)，这个也是image2graph不过在另一个文件夹里，我一开始给你指的位置不太对。这个文件里有直接把生成的node_neighbor （x,y值代表像素位置）进行插值使得两个相邻顶点之间的距离是20个像素左右，这样生成出来的node_neighbor就可以直接用来training了。所以使用这个文件，就不用去管download.py里面的那些代码了。

> 非常感谢您的解答,可能还是得来打扰您,根据您的建议,参考这个repo里面另一个branch中的代码,也就是image2graph.py的文件里边会得到顶点vertices和节点的附近点neighbors,关于生成graph之后与download.py里边的后续与处理过程结合的处理有一些问题想烦扰一下您,
> 1.就是在download.py中下载的操作openstreetmap[md.OSMLoader函数](https://github.com/songtaohe/Sat2Graph/blob/735db431cd7c037b3174c36e65c2b222f591a330/prepare_dataset/download.py#L99)里边在解析xml文件中也就是mapdriver.py文件 [OSMLoader类](https://github.com/songtaohe/Sat2Graph/blob/735db431cd7c037b3174c36e65c2b222f591a330/prepare_dataset/mapdriver.py#L400-L498) ,解析了很多"ways"中的"cycleway","highway"等在二值影像中是没法得到这些信息的得到的
> 2.如果不需要上边的"ways"关键参数的解析信息,那是不是download.py中neighbors[代码](https://github.com/songtaohe/Sat2Graph/blob/735db431cd7c037b3174c36e65c2b222f591a330/prepare_dataset/download.py#L113)信息是以点序列号为索引的,比如(这是一个点的信息,点号,经纬度代表位置信息,node id="259841477" lat="20.1355426" lon="-75.2249005" version="5" timestamp="2016-10-12T22:36:02Z" changeset="42842372" uid="496923" user="abellao"/),而image2graph.py里边得到的neighbors[代码](https://github.com/songtaohe/Sat2Graph/blob/8cf4ed70c51d8581649d34d2db886507f03140e2/prepare_lowres_dataset/image2graph.py#L170-L193),直接将image2graph.py文件中得到的graph图中的neighbors中点的信息是以点的横纵坐标为索引的,比如((1620, 2001)点,影像的坐标x,y代表位置),所以在转换的时候我不太理解的点在于在download.py中找节点邻接点[node_neighbor](https://github.com/songtaohe/Sat2Graph/blob/8cf4ed70c51d8581649d34d2db886507f03140e2/prepare_dataset/download.py#L115-L118)的获取是按照经纬度进行临近点插入的么(n1key代表经度,n2key代表纬度),因为这两个的索引不太一样,所以真的有点混乱,还望指点迷境,不甚感激

**Comment by angleyun** [comment]
非常感谢您的耐心解答

**Comment by angleyun** [comment]
非常抱歉又来打扰您了，关于之前数据预处理的部分，在之前您给的[文件](https://github.com/songtaohe/Sat2Graph/blob/8cf4ed70c51d8581649d34d2db886507f03140e2/prepare_dataset/download.py#L133)中生成可训练的node_neighbor,但是关于数据生成download.py和image2graph.py结合生成训练数据对比20-city dataset有一些问题想请教您。
1.进入网络的训练数据region_%d_refine_gt_graph.p文件和region_%d_graph_gt.pickle文件是依靠node_neighbor进而生成的，但是利用download.py和image2graph.py生成的这两个数据与20citie [dataset中的数据打开之后不一样，同一个地区的，我在存储[文件](https://github.com/songtaohe/Sat2Graph/blob/8cf4ed70c51d8581649d34d2db886507f03140e2/prepare_dataset/download.py#L134)加了转码---就是生成.p和.pickle文件的时候pickle.dump(node_neighbor_refine, open(refine_graph.encode('utf-8'), "wb"))但还是没有解决，所以应该不是存储格式的问题，具体打开如下图:
![Uploading 1.png…](利用download.py生成的训练数据.p文件)
![Uploading 2.png…](20-cities dataset数据集中的.p文件)
利用download.py文件生成的.p文件进网络训练的时候发生错误
2.对比20-cities dataset数据集中和download.py生成的数据发现少了一个region_0_gt_graph.json文件的生成,这个json是不是直接可以用node_neighbor来进行生成?
为我再一次的打扰行为感到抱歉,打扰您了

**Comment by songtaohe** [comment]
1. 关于利用download.py和image2graph.py生成的 .p 文件和下载得到的20city dataset应该是不一样的。 使用代码下载的数据会使用最新的openstreetmap地图，和下载的版本可能不一致。另外下载的20city dataset使用的是python2生成的pickle文件，只看生成的pickle文件本身，可能很难看出什么来。你可以试着把pickle文件读取出来，然后把那个node neighbor里面的点和线段画出来，看看和你所在区域的地图是不是相匹配。

2.那个json文件是用node_neighbor生成的，可以忽略掉。
