### ISSUE TITLE
Which version of Deep Layer Aggregation (DLA) was used?

### ISSUE THREAD

**Issue by corentinh271** [songtaohe/Sat2Graph#5]
From the code in model.py, I could not find out which version of the Deep Layer Aggregation architecture was used for the Sat2Graph model. In your paper I see only mentioned that you used residual blocks for the aggregation function.

Did you use one of the versions presented in the DLA paper or did you implement an architecture of your own?

**Comment by songtaohe** [comment]
> From the code in model.py, I could not find out which version of the Deep Layer Aggregation architecture was used for the Sat2Graph model. In your paper I see only mentioned that you used residual blocks for the aggregation function.
> 
> Did you use one of the versions presented in the DLA paper or did you implement an architecture of your own?



We didn't use their source code, instead, we implemented the model in Figure 4 of their paper https://arxiv.org/pdf/1707.06484.pdf. 

You can find the code [here](https://github.com/songtaohe/Sat2Graph/blob/735db431cd7c037b3174c36e65c2b222f591a330/model/model.py#L335).

I didn't see too many implementation details in their paper about this architecture (maybe I missed it). In our implementation, we use residual blocks in the 'aggregation node' and we use deconvolutional layers for the '2x upsampling'.
