### ISSUE TITLE
您好！请问为什么iD editor使用Sat2Graph没反应呢，谢谢！

### ISSUE THREAD

**Issue by pengshiyong** [songtaohe/Sat2Graph#6]
![2020-12-28_175442](https://user-images.githubusercontent.com/53248854/103205990-cf015f00-4935-11eb-8550-43c08d564f5f.png)

**Comment by songtaohe** [comment]
您好， 我刚才检查了一下服务器，我这边好像还是可以使用的，我用的chrome浏览器。可以提供一下你那边具体的环境吗？如果有javascript console的log信息会更好。谢谢！

**Comment by pengshiyong** [comment]
> 您好， 我刚才检查了一下服务器，我这边好像还是可以使用的，我用的chrome浏览器。可以提供一下你那边具体的环境吗？如果有javascript console的log信息会更好。谢谢！

您好，十分感谢您的回复！刚刚重新试了一下，能成功运行了。之前也是用的chrome，不知道是不是网络原因。抱歉，打扰您了！

**Comment by songtaohe** [comment]
> > 您好， 我刚才检查了一下服务器，我这边好像还是可以使用的，我用的chrome浏览器。可以提供一下你那边具体的环境吗？如果有javascript console的log信息会更好。谢谢！
> 
> 您好，十分感谢您的回复！刚刚重新试了一下，能成功运行了。之前也是用的chrome，不知道是不是网络原因。抱歉，打扰您了！

可以用了就好！

**Comment by pengshiyong** [comment]
> > > 您好， 我刚才检查了一下服务器，我这边好像还是可以使用的，我用的chrome浏览器。可以提供一下你那边具体的环境吗？如果有javascript console的log信息会更好。谢谢！
> > 
> > 
> > 您好，十分感谢您的回复！刚刚重新试了一下，能成功运行了。之前也是用的chrome，不知道是不是网络原因。抱歉，打扰您了！
> 
> 可以用了就好！
好的谢谢，感谢您的贡献！

**Comment by Artoria2e5** [comment]
我这儿网好像又不好使了：
```
index.js:47 POST http://128.30.198.28:8123/ net::ERR_EMPTY_RESPONSE
window.fetch @ index.js:47
checkStatus @ sat2graphInteract.js:441
:8080/#background=Ma…9.77245/121.52411:1 Uncaught (in promise) TypeError: Failed to fetch
```

似乎还一直在自动重试，建议加个限制别自己把自己 DDoS 坏了……
