### ISSUE TITLE
model file errors  TypeError: Value passed to parameter 'paddings' has DataType float32 not in list of allowed values: int32, int64

### ISSUE THREAD

**Issue by makaay2077** [songtaohe/Sat2Graph#7]
I want to work model files but I keep getting this error (train.py , localserver.py ..)

Traceback (most recent call last):
  File "localserver.py", line 22, in <module>
    model = Sat2GraphModel(sess, image_size=352, resnet_step = 8, batchsize = 1, channel = 12, mode = "test")
  File "/content/Sat2Graph/model/model.py", line 66, in __init__
    self.imagegraph_output = self.BuildDeepLayerAggregationNetWithResnet(self.input_sat, input_ch = image_ch, output_ch =2 + MAX_DEGREE * 4 + (2 if self.joint_with_seg==True else 0), ch=channel)
  File "/content/Sat2Graph/model/model.py", line 342, in BuildDeepLayerAggregationNetWithResnet
    conv1, _, _ = common.create_conv_layer('cnn_l1', net_input, input_ch, ch, kx = 5, ky = 5, stride_x = 1, stride_y = 1, is_training = self.is_training, batchnorm = False)
  File "/content/Sat2Graph/model/tf_common_layer.py", line 56, in create_conv_layer
    input_tensor = tf.pad(input_tensor, [[0, 0], [kx/2, kx/2], [kx/2, kx/2], [0, 0]], mode="CONSTANT")
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/array_ops.py", line 2840, in pad
    result = gen_array_ops.pad(tensor, paddings, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_array_ops.py", line 6399, in pad
    "Pad", input=input, paddings=paddings, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 632, in _apply_op_helper
    param_name=input_name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 61, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'paddings' has DataType float32 not in list of allowed values: int32, int64

**Comment by songtaohe** [comment]
> I want to work model files but I keep getting this error (train.py , localserver.py ..)
> 
> Traceback (most recent call last):
> File "localserver.py", line 22, in
> model = Sat2GraphModel(sess, image_size=352, resnet_step = 8, batchsize = 1, channel = 12, mode = "test")
> File "/content/Sat2Graph/model/model.py", line 66, in **init**
> self.imagegraph_output = self.BuildDeepLayerAggregationNetWithResnet(self.input_sat, input_ch = image_ch, output_ch =2 + MAX_DEGREE * 4 + (2 if self.joint_with_seg==True else 0), ch=channel)
> File "/content/Sat2Graph/model/model.py", line 342, in BuildDeepLayerAggregationNetWithResnet
> conv1, _, _ = common.create_conv_layer('cnn_l1', net_input, input_ch, ch, kx = 5, ky = 5, stride_x = 1, stride_y = 1, is_training = self.is_training, batchnorm = False)
> File "/content/Sat2Graph/model/tf_common_layer.py", line 56, in create_conv_layer
> input_tensor = tf.pad(input_tensor, [[0, 0], [kx/2, kx/2], [kx/2, kx/2], [0, 0]], mode="CONSTANT")
> File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/array_ops.py", line 2840, in pad
> result = gen_array_ops.pad(tensor, paddings, name=name)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_array_ops.py", line 6399, in pad
> "Pad", input=input, paddings=paddings, name=name)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 632, in _apply_op_helper
> param_name=input_name)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 61, in _SatisfiesTypeConstraint
> ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
> TypeError: Value passed to parameter 'paddings' has DataType float32 not in list of allowed values: int32, int64

Hi, the code is for python 2. If you run it with python 3, you need to (at least) change all the division operator from "/" to "//" for integer division. The "/" operator in python 3 will give you 'float' numbers and that should be the reason for this error.
