### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by Dicksonchin93** [songtaohe/Sat2Graph#8]
what is the number 16 used for in the below code?
https://github.com/songtaohe/Sat2Graph/blob/93ee6037312179acba720d65e7a5853444cccccb/model/dataloader.py#L189-L190

**Comment by songtaohe** [comment]
> what is the number 16 used for in the below code?
> https://github.com/songtaohe/Sat2Graph/blob/93ee6037312179acba720d65e7a5853444cccccb/model/dataloader.py#L189-L190

The goal of this line (and similar lines in other places) is to remove vertices near the boundary of the big tile (2048 by 2048). If I remember correctly, it may not need to be 16, any number greater than 2 should work here.
