### ISSUE TITLE
Interested in pseudo code of decoder

### ISSUE THREAD

**Issue by Dicksonchin93** [songtaohe/Sat2Graph#9]
Great work you have done here, I wanted to see how you handled the distance computation for the two vertexes connected to the same edge (whether you computed distance for one edge or on both edge) but the paper didn't emphasize a lot on the implementation of the decoder, code looks rather complicated and wonder if there is some decoder pseudocode to look at?

**Comment by songtaohe** [comment]
> Great work you have done here, I wanted to see how you handled the distance computation for the two vertexes connected to the same edge (whether you computed distance for one edge or on both edge) but the paper didn't emphasize a lot on the implementation of the decoder, code looks rather complicated and wonder if there is some decoder pseudocode to look at?

For your first half of the question, the answer is that we only compute the distance for one edge. In this case, even when one edge is missing, we can still connect the two vertices. 

Indeed, the implementation of the decoder is complicated. I will write down the pseudocode and some detailed explanations and post them by the end of this week.

**Comment by Dicksonchin93** [comment]
for step1(b) it feels more like it is using either one of  a-->b or b<--c to find b but not both as the values get overrided here https://github.com/songtaohe/Sat2Graph/blob/7579cfcaf173db3f3c94ceb0b2f8d40878a2a204/model/decoder.py#L546

thanks for all the explanations! especially on step 2

**Comment by songtaohe** [comment]
> for step1(b) it feels more like it is using either one of a-->b or b<--c to find b but not both as the values get overrided here
> 
> https://github.com/songtaohe/Sat2Graph/blob/7579cfcaf173db3f3c94ceb0b2f8d40878a2a204/model/decoder.py#L546
> 
> thanks for all the explanations! especially on step 2

Yeah, you are right. In step1(b), I should write 'In this case, we use the edges a-->b OR b<--c to recover b'.
